name: flake8 version check

on:
  schedule:
    # run the action always at 1:11 UTC (i.e. 3:11 CEST)
    - cron:  '11 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install requests tomli
      - name: Perform flake8 version check
        run: python .github/workflows/maintenance.py check